force-app/main/default/objects/ESACHS_EventNotificacionProspecto__e/ESACHS_EventNotificacionProspecto__e.object-meta.xml
<CustomObject>
    <description>Platform Event para generar los POST en chatter desde contexto de Trigger.</description>
    <label>Notificación Prospecto</label>
    <pluralLabel>Notificaciones Prospectos</pluralLabel>
</CustomObject>

force-app/main/default/objects/ESACHS_EventNotificacionProspecto__e/fields/ESACHS_PostBody__c.field-meta.xml
<CustomField>
    <fullName>ESACHS_PostBody__c</fullName>
    <label>Post Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ESACHS_EventNotificacionProspecto__e/fields/ESACHS_PostParentId__c.field-meta.xml
<CustomField>
    <fullName>ESACHS_PostParentId__c</fullName>
    <label>Post Parent Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESACHS_EventNotificacionLeadHandler.cls
/*
* @description:  
* @author: Nuria Durán Rodríguez (INETUM)
* @version: 1.0 
*/
public with sharing class ESACHS_EventNotificacionLeadHandler {

    /**
    * @name: postChatter() method
    * @author: Nuria Durán Rodríguez (INETUM)
    * @description: Crea una notificación de chatter a través de los campos que reciba del Platform Event
    */
    public static void postChatter(List<ESACHS_EventNotificacionProspecto__e> eventNotificationLeadLst){
        List<FeedItem> feedItemPostLst = new List<FeedItem>();
        for (ESACHS_EventNotificacionProspecto__e eventNotifLeadTmp :eventNotificationLeadLst ){
            FeedItem post = new FeedItem();
            post.ParentId = eventNotifLeadTmp.ESACHS_PostParentId__c;
            post.Body = eventNotifLeadTmp.ESACHS_PostBody__c;
            feedItemPostLst.add(post);
        }

        if (feedItemPostLst.size() > 0){
            insert feedItemPostLst;
        }
    } 
}