force-app/main/default/objects/ESACHS_EventNotificacionProspecto__e/ESACHS_EventNotificacionProspecto__e.object-meta.xml
<CustomObject>
    <description>Platform Event para generar los POST en chatter desde contexto de Trigger.</description>
    <label>Notificación Prospecto</label>
    <pluralLabel>Notificaciones Prospectos</pluralLabel>
</CustomObject>

force-app/main/default/objects/ESACHS_EventNotificacionProspecto__e/fields/ESACHS_PostBody__c.field-meta.xml
<CustomField>
    <fullName>ESACHS_PostBody__c</fullName>
    <label>Post Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ESACHS_EventNotificacionProspecto__e/fields/ESACHS_PostParentId__c.field-meta.xml
<CustomField>
    <fullName>ESACHS_PostParentId__c</fullName>
    <label>Post Parent Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESACHS_EventNotificacionLeadHandler_test.cls
/*
* @description: Clase Test para ESACHS_EventNotificacionLeadHandler_test
* @author: Nuria Durán Rodríguez (INETUM)
* @version: 1.0 
*/
@isTest
public class ESACHS_EventNotificacionLeadHandler_test {

   /**
    * @name: postChatterTest() method
    * @author: Nuria Durán Rodríguez (INETUM)
    * @description: Envia una notificación de advertencia mediante Chatter al propietario del prospecto si en un plazo de 5 días hábiles desde la creación del prospecto este no ha sido convertido.
    */ 
    static testMethod void postChatterTest() {
        //Lo inserto porque es contexto de trigger After Insert:
        //Recupero Usuario Administrador:
        User userAdmin = ESACHS_FactoriaDatosTest.createUserAdmin();
        //Creo dataset de Leads:
        List<Lead> leadLst = ESACHS_FactoriaDatosTest.createNewLeadCentroSalud(2);
        for (Lead leadTmp : leadLst){
            leadTmp.OwnerId = userAdmin.Id;
        }
       
        insert leadLst;    
        
        List<ESACHS_EventNotificacionProspecto__e> eventNotificationLeadLst = new List<ESACHS_EventNotificacionProspecto__e>();
    
        //Compruebo que inicialmente no hay post en chatter:
        List<FeedItem> postChatterLeadInit = [SELECT Id, ParentId FROM FeedItem LIMIT 200];
        System.assert(postChatterLeadInit.size() == 0);
        
        for (Lead leadTmp : leadLst){
            ESACHS_EventNotificacionProspecto__e eventNotificationLead = new ESACHS_EventNotificacionProspecto__e();
            eventNotificationLead.ESACHS_PostParentId__c = leadTmp.OwnerId;
            eventNotificationLead.ESACHS_PostBody__c = 'Test Event';
            eventNotificationLeadLst.add(eventNotificationLead);
        }

      
        Test.startTest();
        ESACHS_EventNotificacionLeadHandler.postChatter(eventNotificationLeadLst);
        Test.stopTest();
    

        //Compruebo que se han generado post en chatter:
        List<FeedItem> postChatterLead = [SELECT Id, ParentId FROM FeedItem LIMIT 200];
        System.assert(postChatterLead.size() >0);
        
    }
 
}